name: effect-env
dependencies:
    - python=2.7.12=1
    - psycopg2
    - spacy
    - pip:
        - digEntityMerger
        - digSparkUtil
        - xmljson
        - requests
        - digExtractor
        - digRegexExtractor
        - digEmailExtractor
        - jsonpath-rw
        - jsonpath-rw-ext
        - hdfs
        - python-crfsuite
        - sshtunnel
